name: XP In The Jar
main: cc.thedudeguy.xpinthejar.XPInTheJar
version: 1.1.0
description: Musha ring dum-a do dum-a da. There's XP in the jar-o. Store XP in a container block.
website: http://dev.bukkit.org/server-mods/xp-jar/
author: Chris Churchwell (thedudeguy)
database: true